services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    env_file:
      - .env
    environment:
      - DB_HOST=host.docker.internal
      # - DB_HOST=192.168.200.8
      - DB_PORT=5432
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_DATABASE=postgres
      



